'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Synchro.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à ACLs could not be changed..
        '''</summary>
        Friend ReadOnly Property strAclFailed() As String
            Get
                Return ResourceManager.GetString("strAclFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Do you want to continue?.
        '''</summary>
        Friend ReadOnly Property strAskContinue() As String
            Get
                Return ResourceManager.GetString("strAskContinue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Do you want to create the file .
        '''</summary>
        Friend ReadOnly Property strAskCreateFile() As String
            Get
                Return ResourceManager.GetString("strAskCreateFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Do you want to create the folder .
        '''</summary>
        Friend ReadOnly Property strAskCreateFolder() As String
            Get
                Return ResourceManager.GetString("strAskCreateFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Do you really want to delete the file .
        '''</summary>
        Friend ReadOnly Property strAskDeleteFile() As String
            Get
                Return ResourceManager.GetString("strAskDeleteFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Do you really want to delete the folder .
        '''</summary>
        Friend ReadOnly Property strAskDeleteFolder() As String
            Get
                Return ResourceManager.GetString("strAskDeleteFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Attributes could not be changed..
        '''</summary>
        Friend ReadOnly Property strAttributesFailed() As String
            Get
                Return ResourceManager.GetString("strAttributesFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à ACLs changed on .
        '''</summary>
        Friend ReadOnly Property strChangeACLs() As String
            Get
                Return ResourceManager.GetString("strChangeACLs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Attributes changed on .
        '''</summary>
        Friend ReadOnly Property strChangeAttributes() As String
            Get
                Return ResourceManager.GetString("strChangeAttributes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à The copy failed..
        '''</summary>
        Friend ReadOnly Property strCopyFailed() As String
            Get
                Return ResourceManager.GetString("strCopyFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à File copied: .
        '''</summary>
        Friend ReadOnly Property strCopyfile() As String
            Get
                Return ResourceManager.GetString("strCopyfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Folder created: .
        '''</summary>
        Friend ReadOnly Property strCreateFolder() As String
            Get
                Return ResourceManager.GetString("strCreateFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à The deletion failed.
        '''</summary>
        Friend ReadOnly Property strDeleteFailed() As String
            Get
                Return ResourceManager.GetString("strDeleteFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à File deleted: .
        '''</summary>
        Friend ReadOnly Property strDeleteFile() As String
            Get
                Return ResourceManager.GetString("strDeleteFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Folder deleted:.
        '''</summary>
        Friend ReadOnly Property strDeleteFolder() As String
            Get
                Return ResourceManager.GetString("strDeleteFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Log is impossible: .
        '''</summary>
        Friend ReadOnly Property strErrorLog() As String
            Get
                Return ResourceManager.GetString("strErrorLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à File excluded:.
        '''</summary>
        Friend ReadOnly Property strExcludedFile() As String
            Get
                Return ResourceManager.GetString("strExcludedFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Folder excluded:.
        '''</summary>
        Friend ReadOnly Property strExcludedFolder() As String
            Get
                Return ResourceManager.GetString("strExcludedFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à  ms.
        '''</summary>
        Friend ReadOnly Property strMilliseconds() As String
            Get
                Return ResourceManager.GetString("strMilliseconds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Option /a  : Copy file ACLs.
        '''</summary>
        Friend ReadOnly Property strOptionA() As String
            Get
                Return ResourceManager.GetString("strOptionA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Option /d : Preserve newer files.
        '''</summary>
        Friend ReadOnly Property strOptionD() As String
            Get
                Return ResourceManager.GetString("strOptionD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Option /e  : Copy empty subdirectories.
        '''</summary>
        Friend ReadOnly Property strOptionE() As String
            Get
                Return ResourceManager.GetString("strOptionE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Option /k  : Copy file attributes.
        '''</summary>
        Friend ReadOnly Property strOptionK() As String
            Get
                Return ResourceManager.GetString("strOptionK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Option /r  : Overwrite Read-Only files.
        '''</summary>
        Friend ReadOnly Property strOptionR() As String
            Get
                Return ResourceManager.GetString("strOptionR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Option /s  : Copy subdirectories.
        '''</summary>
        Friend ReadOnly Property strOptionS() As String
            Get
                Return ResourceManager.GetString("strOptionS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Option /Samba : Accept a little difference when comparing file dates (1&apos;&apos; by default).
        '''</summary>
        Friend ReadOnly Property strOptionSamba() As String
            Get
                Return ResourceManager.GetString("strOptionSamba", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Option /u  : Copy only existing files.
        '''</summary>
        Friend ReadOnly Property strOptionU() As String
            Get
                Return ResourceManager.GetString("strOptionU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Option /z  : Synchronize.
        '''</summary>
        Friend ReadOnly Property strOptionZ() As String
            Get
                Return ResourceManager.GetString("strOptionZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à ?.
        '''</summary>
        Friend ReadOnly Property strQuestionMark() As String
            Get
                Return ResourceManager.GetString("strQuestionMark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à The object size could not be read.
        '''</summary>
        Friend ReadOnly Property strSizeFailed() As String
            Get
                Return ResourceManager.GetString("strSizeFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Source     : .
        '''</summary>
        Friend ReadOnly Property strSource() As String
            Get
                Return ResourceManager.GetString("strSource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à The source folder does not exist. Operation cancelled.
        '''</summary>
        Friend ReadOnly Property strSourceDirFailed() As String
            Get
                Return ResourceManager.GetString("strSourceDirFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Synchro is preparing the synchronization (this may take a little time...).
        '''</summary>
        Friend ReadOnly Property strSyncPreparing() As String
            Get
                Return ResourceManager.GetString("strSyncPreparing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Synchronization started.
        '''</summary>
        Friend ReadOnly Property strSyncStart() As String
            Get
                Return ResourceManager.GetString("strSyncStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Target     : .
        '''</summary>
        Friend ReadOnly Property strTarget() As String
            Get
                Return ResourceManager.GetString("strTarget", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à The target folder could not be created. Operation cancelled.
        '''</summary>
        Friend ReadOnly Property strTargetDirFailed() As String
            Get
                Return ResourceManager.GetString("strTargetDirFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à The target folder path is incorrect.
        '''</summary>
        Friend ReadOnly Property strTargetDirIncorrect() As String
            Get
                Return ResourceManager.GetString("strTargetDirIncorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Operation cancelled: the target folder is inside the source.
        '''</summary>
        Friend ReadOnly Property strTargetInSource() As String
            Get
                Return ResourceManager.GetString("strTargetInSource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Time difference allowed: .
        '''</summary>
        Friend ReadOnly Property strTimeDifferenceAllowed() As String
            Get
                Return ResourceManager.GetString("strTimeDifferenceAllowed", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
