'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Synchro.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lezard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lezard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à ?.
        '''</summary>
        Friend ReadOnly Property strAsk() As String
            Get
                Return ResourceManager.GetString("strAsk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Do you want to continue (all changes since the last time the file was saved will be lost)?.
        '''</summary>
        Friend ReadOnly Property strAskIgnoreChanges() As String
            Get
                Return ResourceManager.GetString("strAskIgnoreChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Do you want to save the file .
        '''</summary>
        Friend ReadOnly Property strAskSaveFile() As String
            Get
                Return ResourceManager.GetString("strAskSaveFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Folder synchronization utility.
        '''</summary>
        Friend ReadOnly Property strAssemblyDescription() As String
            Get
                Return ResourceManager.GetString("strAssemblyDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à A synchronization is runnig. You must stop it or wait for it to finish before you can exit..
        '''</summary>
        Friend ReadOnly Property strCantClose() As String
            Get
                Return ResourceManager.GetString("strCantClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à The synchronization was cancelled by the user.
        '''</summary>
        Friend ReadOnly Property strCopyCancelled() As String
            Get
                Return ResourceManager.GetString("strCopyCancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à The synchronization failed.
        '''</summary>
        Friend ReadOnly Property strCopyFailed() As String
            Get
                Return ResourceManager.GetString("strCopyFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à File copied: .
        '''</summary>
        Friend ReadOnly Property strCopyfile() As String
            Get
                Return ResourceManager.GetString("strCopyfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à The synchronization is done.
        '''</summary>
        Friend ReadOnly Property strCopyFinished() As String
            Get
                Return ResourceManager.GetString("strCopyFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à The file could not be read.
        '''</summary>
        Friend ReadOnly Property strErrReadFile() As String
            Get
                Return ResourceManager.GetString("strErrReadFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à The file is already open.
        '''</summary>
        Friend ReadOnly Property strFileAlreadyOpen() As String
            Get
                Return ResourceManager.GetString("strFileAlreadyOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à There was nothing to do. Synchronization done..
        '''</summary>
        Friend ReadOnly Property strNothingToDo() As String
            Get
                Return ResourceManager.GetString("strNothingToDo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Synchro [Synchro File]  [/Source=SourceFiolder /Target=TargetFolder] [/options] [/go].
        '''</summary>
        Friend ReadOnly Property strSyntaxDetail() As String
            Get
                Return ResourceManager.GetString("strSyntaxDetail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Example: Synchro /Source=C:\Source /Target=C:\Target /s /e /l=C:\Synchro.log /go.
        '''</summary>
        Friend ReadOnly Property strSyntaxExample() As String
            Get
                Return ResourceManager.GetString("strSyntaxExample", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Syntax: .
        '''</summary>
        Friend ReadOnly Property strSyntaxTitle() As String
            Get
                Return ResourceManager.GetString("strSyntaxTitle", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
